version: '3'

services:
  graffiti-app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - graffiti-data:/app/data
    restart: unless-stopped

volumes:
  graffiti-data:
    # This creates a named volume to persist your graffiti walls data
